text_clean: True
data_path: "./data/刑期预测赛道一期数据_训练集"
stop_word: "./config/stop-word"
tokenizer: "./output/tokenizer.pickle"
save_model: "./output/best_model.h5"
samples_path: "./output/samples"
labels_path: "./output/labels"
train_portion: 0.8
vocab_size: 1000
embedding_dim: 256
max_length: 512
batch_size: 128
num_epochs: 10
trunc_type: "post"
padding_type: "post"
oov_tok: "<OOV>"
select_model: "cnn_regression"
dropout: 0.45
